[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.1"
color-eyre = "0.6.2"
crossterm = "0.25.0"
custom_error = "1.9.2"
itertools = "0.10.5"
lazy_static = "1.4.0"
nom = "7.1.1"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
